---
- name: Ensure custom config is loaded
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      PermitRootLogin yes
      PermitEmptyPasswords no
      PasswordAuthentication no
    insertbefore: BOF
    validate: sshd -f %s -t

- name: Set ssh authorized_keys
  authorized_key:
    key: "{{ ssh_authorized_keys|join('\n') }}"
    user: "{{ ansible_user }}"
    exclusive: false
